AddCSLuaFile()

game.AddParticles( "particles/tornado_effects_01.pcf") 
game.AddParticles( "particles/tornado_effects_02.pcf") 
game.AddParticles( "particles/tornado_effects_03.pcf") 
game.AddParticles( "particles/tornado_effects_04.pcf") 
game.AddParticles( "particles/tornado_effects_05.pcf") 
game.AddParticles( "particles/tornado_effects_06.pcf") 
game.AddParticles( "particles/tornado_effects_07.pcf") 
game.AddParticles( "particles/gustnado_effect.pcf") 
game.AddParticles( "particles/firenado_hd.pcf") 
game.AddParticles( "particles/firenado_hf.pcf") 
game.AddParticles( "particles/dust_devil_effect.pcf") 
game.AddParticles( "particles/water_splash_effect.pcf") 
game.AddParticles( "particles/damagetypes.pcf") 
game.AddParticles( "particles/whirlpool_effect.pcf") 
game.AddParticles( "particles/earthquake_effect.pcf") 
game.AddParticles( "particles/tsunami_splash_effect.pcf") 
game.AddParticles( "particles/tar_pit_effect.pcf") 
game.AddParticles( "particles/bugswarm_effect.pcf") 
game.AddParticles( "particles/martian_tornado.pcf")

