game.AddParticles("particles/galaxy_blood_particles.pcf")
PrecacheParticleSystem("exit_blood_small")
PrecacheParticleSystem("exit_blood_large")
PrecacheParticleSystem("exit_blood_explosion")
PrecacheParticleSystem("blood_stream_goop")