include("shared.lua")
include("sh_anim.lua")
include("sh_bullet.lua")
include("sh_replicate.lua")
include("sh_holster_deploy.lua")
include("sh_reload.lua")
include("sh_spray.lua")
include("sh_worldmodel.lua")
include("sh_attachment.lua")
include("sh_fake.lua")
include("sh_ammo.lua")
include("cl_camera.lua")
include("cl_camera_wep.lua")
include("cl_optics.lua")

net.Receive("SoundBCST",function()
	local wep = net.ReadEntity()
	local sdist = net.ReadString()
	if LocalPlayer():EyePos():Distance(wep:GetPos()) > 500 then
		wep:EmitSound(wep.DistSound,125,100,1,CHAN_WEAPON,0,0)
	end
end)