include("shared.lua")
include("sh_bullet.lua")
include("sh_worldmodel.lua")
include("sh_reload.lua")
include("sh_anim.lua")
include("sh_icon.lua")
include("sh_spray.lua")

AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_bullet.lua")
AddCSLuaFile("sh_icon.lua")
AddCSLuaFile("cl_camera.lua")
AddCSLuaFile("sh_worldmodel.lua")
AddCSLuaFile("sh_reload.lua")
AddCSLuaFile("sh_anim.lua")
AddCSLuaFile("sh_spray.lua")