game.AddParticles("particles/galaxy_blood_particles.pcf")
PrecacheParticleSystem("exit_blood_small")
PrecacheParticleSystem("exit_blood_large")
PrecacheParticleSystem("exit_blood_explosion")
PrecacheParticleSystem("blood_stream_goop")

game.AddParticles("particles/matin_weapon_fx_mwb.pcf")

PrecacheParticleSystem("matin_mw_muzzleflash_ar")
PrecacheParticleSystem("matin_mw_muzzleflash_ar2")
PrecacheParticleSystem("matin_mw_muzzleflash_ar3")
PrecacheParticleSystem("matin_mw_muzzleflash_ar4")
PrecacheParticleSystem("matin_mw_muzzleflash_ar5")
PrecacheParticleSystem("matin_mw_muzzleflash_ar6")
PrecacheParticleSystem("matin_mw_muzzleflash_ar7")
PrecacheParticleSystem("matin_mw_muzzleflash_pl")
PrecacheParticleSystem("matin_mw_muzzleflash_dmr")
PrecacheParticleSystem("matin_mw_muzzleflash_lmg")
PrecacheParticleSystem("matin_mw_muzzleflash_smg")
PrecacheParticleSystem("matin_mw_muzzleflash_smg2")
PrecacheParticleSystem("matin_mw_muzzleflash_smg3")
PrecacheParticleSystem("matin_mw_muzzleflash_sg")
PrecacheParticleSystem("matin_mw_muzzleflash_sr")
PrecacheParticleSystem("matin_mw_muzz_sg_db_f")
PrecacheParticleSystem("matin_mw_muzzleflash_sup")
-- Color 
PrecacheParticleSystem("matin_mw_color_blue")
PrecacheParticleSystem("matin_mw_color_blue2")
PrecacheParticleSystem("matin_mw_color_blue3")
PrecacheParticleSystem("matin_mw_color_sup_blue")
PrecacheParticleSystem("matin_mw_color_purple")
PrecacheParticleSystem("matin_mw_color_purple_sg")
PrecacheParticleSystem("matin_mw_muzz_sg_db_f_purple")
-- unique
PrecacheParticleSystem("matin_mw_muzzleflash_ae")
PrecacheParticleSystem("matin_mw_muzzleflash_ak")
PrecacheParticleSystem("matin_mw_muzzleflash_p90")
PrecacheParticleSystem("matin_mw_muzzleflash_357")
PrecacheParticleSystem("matin_mw_muzzleflash_pixel")
PrecacheParticleSystem("matin_mw_muzzleflash_10f")


