ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "База Гранаты"
ENT.Author = "V-City"
ENT.Category = "Homigrad"
ENT.Spawnable = true
ENT.TypeGren = "Frag"
ENT.HasLever = true
ENT.RequiresLever = true
ENT.Delay = 3
ENT.ImpactSound = {"weapons/darsu_eft/grenades/grenade_collision_concrete1.ogg","weapons/darsu_eft/grenades/grenade_collision_concrete2.ogg","weapons/darsu_eft/grenades/grenade_collision_concrete3.ogg"}