SWEP.Base = "weapon_870"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.PrintName = "Beneli Nova"
SWEP.Author = "Homigrad"
SWEP.Instructions = "\n11 выстрелов в секунду\n125 Урона\n0.05 Разброс"
SWEP.Category = "Оружие - Дробовики"
SWEP.Slot = 2
SWEP.SlotPos = 2
SWEP.ViewModel = ""
SWEP.WorldModel = "models/weapons/tfa_ins2/w_nova.mdl"

SWEP.weaponInvCategory = 1
SWEP.ShellEject = "ShotgunShellEject"
SWEP.AutomaticDraw = false
SWEP.UseCustomWorldModel = false
SWEP.TwoHanded = true
SWEP.Primary.ClipSize = 8
SWEP.Primary.DefaultClip = 8
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "12/70 gauge"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 15.625--в общем 125
SWEP.Primary.Spread = Vector(0.05, 0.05, 0.05)
SWEP.Primary.Force = 2
SWEP.NumBullet = 8
SWEP.Primary.Sound = {"sounds_zcity/saiga12/close.wav", 80, 110, 100}
SWEP.Primary.RandomSounds = {"sounds_zcity/saiga12/close.wav","sounds_zcity/saiga12/close.wav","sounds_zcity/saiga12/close.wav","sounds_zcity/saiga12/close.wav"} -- костыль
SWEP.Primary.Wait = 1/11
SWEP.DeploySnd = {"homigrad/weapons/draw_hmg.mp3", 55, 100, 110}
SWEP.HolsterSnd = {"homigrad/weapons/hmg_holster.mp3", 55, 100, 110}
SWEP.HoldType = "ar2"
SWEP.ReloadHold = "pistol"
SWEP.ZoomPos = Vector(-1.3,0,35)
SWEP.RHandPos = Vector(-5, -2, 0)
SWEP.LHandPos = Vector(7, -2, -2)
SWEP.SprayRand = {Angle(-0.2, -0.4, 0), Angle(-0.4, 0.4, 0)}
SWEP.Ergonomics = 0.9
SWEP.AnimShootMul = 5
SWEP.AnimShootHandMul = 300
SWEP.AnimStart_Draw = 0
SWEP.AnimStart_Insert = 0
SWEP.AnimInsert = 0.1
SWEP.AnimDraw = 0.1
SWEP.Penetration = 7
SWEP.ReloadTime = 0.75
SWEP.AnimInsert = 0.1
SWEP.AnimDraw = 0.3
SWEP.ReloadDrawTime = 0.1
SWEP.ReloadDrawCooldown = 0.5
SWEP.ReloadInsertTime = 0.1
SWEP.ReloadInsertCooldown = 0.25
SWEP.ReloadInsertCooldownFire = 0.1
SWEP.lengthSub = 20
SWEP.handsAng = Angle(0, 0, 0)
SWEP.AmmoTypes = {
	[1] = {"12/70 gauge", Vector(0.05, 0.05, 0.05), 16, 3, 8, false, 1},
	[2] = {"12/70 beanbag", Vector(0.005, 0.005, 0.005), 16, 8, 1, true, 2},
}
SWEP.attPos = Vector(7, 0, 0)
SWEP.attAng = Angle(0,0,0)
SWEP.EjectPos = Vector(17,6,-3.5)
SWEP.EjectAng = Angle(0,0,-60)
SWEP.holsteredBone = "ValveBiped.Bip01_Spine2"
SWEP.holsteredPos = Vector(16,-1.4,0)
SWEP.holsteredAng = Angle(-10, 180, 0)
SWEP.IconAng = Angle(-20,0,0)
SWEP.IconPos = Vector(5.4,30,-8)
SWEP.UseCustomWorldModel = true
SWEP.WorldPos = Vector(-2, -0.2, -1)
SWEP.WorldAng = Angle(0, -0, 0)
SWEP.DistSound = "toz_shotgun/toz_dist.wav"

SWEP.BoltBone = "W_BOLT_SHOT"
SWEP.BoltMul = Vector(0,1,0)

SWEP.CustomAnim = true