SWEP.Base = "homigrad_base"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.PrintName = "SCAR"
SWEP.Author = "Homigrad"
SWEP.Instructions = "\n10 выстрелов в секунду\n45 Урона\n0.0025 Разброс"
SWEP.Category = "Оружие - Винтовки"
SWEP.Slot = 2
SWEP.SlotPos = 2
SWEP.ViewModel = ""
SWEP.WorldModel = "models/weapons/arccw_go/v_rif_scar.mdl"
SWEP.weaponInvCategory = 1
SWEP.Primary.ClipSize = 15
SWEP.Primary.DefaultClip = 15
SWEP.Primary.Automatic = true
SWEP.Primary.Ammo = "5.56x45 mm"
SWEP.Primary.Cone = 0
SWEP.Primary.Spread = 0.0005
SWEP.Primary.Damage = 45
SWEP.Primary.Force = 30
SWEP.Primary.Sound = {"pwb/weapons/hk416/shoot.wav", 85, 100, 100}
SWEP.Primary.Wait = 1 / 10
SWEP.DeploySnd = {"homigrad/weapons/draw_hmg.mp3", 55, 100, 110}
SWEP.HolsterSnd = {"homigrad/weapons/hmg_holster.mp3", 55, 100, 110}
SWEP.ReloadTime = 2
SWEP.ReloadSound = "weapons/ar2/ar2_reload.wav"
SWEP.HoldType = "ar2"
SWEP.ZoomPos = Vector(0.02,-0.065,32)
SWEP.RHandPos = Vector(-12, -1, 4)
SWEP.LHandPos = Vector(7, -2, -2)
SWEP.attPos = Vector(4.9, 0.8, 40)
SWEP.attAng = Angle(-0.2,-0.9,0)
SWEP.TwoHanded = true
SWEP.IconAng = Angle(-15,0,0)
SWEP.IconPos = Vector(-3,55,-3.8)

SWEP.Ergonomics = 0.75
SWEP.Penetration = 15
SWEP.ShellEject = "EjectBrass_338Mag"
SWEP.EjectAng = Angle(180, 0, 0)
SWEP.WorldPos = Vector(-9, -6, -7)
SWEP.WorldAng = Angle(0, -0, 0)
SWEP.UseCustomWorldModel = true
SWEP.lengthSub = 15
SWEP.DistSound = "arccw_go/scar20/scar20_distant_01.wav"
SWEP.holsteredBone = "ValveBiped.Bip01_Spine2"
SWEP.holsteredPos = Vector(29,-2.5, 10)
SWEP.holsteredAng = Angle(-10, 180, 0)
SWEP.EjectPos = Vector(17,6,-3.5)
SWEP.EjectAng = Angle(0,0,-60)

SWEP.BoltBone = "v_weapon.SCAR_Bolt"
SWEP.BoltMul = Vector(0,0,-5.5)