SWEP.Base = "homigrad_base"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.PrintName = "Glock 17"
SWEP.Author = "Homigrad"
SWEP.Instructions = "\n6 выстрелов в секунду\n15 Урона\n0.015 Разброс"
SWEP.Category = "Оружие - Пистолеты"
SWEP.Slot = 2
SWEP.SlotPos = 2
SWEP.ViewModel = ""
SWEP.WorldModel = "models/weapons/arccw_go/v_pist_glock.mdl"

SWEP.weaponInvCategory = 2
SWEP.ShellEject = "EjectBrass_9mm"
SWEP.Primary.ClipSize = 17
SWEP.Primary.DefaultClip = 17
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "9x19 mm Parabellum"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 25
SWEP.Primary.Sound = {"arccw_go/glock18/glock18-1.wav", 75, 100, 100}
SWEP.Primary.Force = 25
SWEP.Primary.Spread = 0.015
SWEP.Primary.Wait = 1 / 6
SWEP.ReloadTime = 2.3
SWEP.DeploySnd = {"homigrad/weapons/draw_pistol.mp3", 55, 100, 110}
SWEP.HolsterSnd = {"homigrad/weapons/holster_pistol.mp3", 55, 100, 110}
SWEP.HoldType = "revolver"
SWEP.ZoomPos = Vector(-0.8, -0.08, 20)
SWEP.RHandPos = Vector(-5, -0.5, -1)
SWEP.LHandPos = false
SWEP.SprayRand = {Angle(-0.03, -0.03, 0), Angle(-0.05, 0.03, 0)}
SWEP.Ergonomics = 1.2
SWEP.Penetration = 7
SWEP.WorldPos = Vector(-13, -4.1, -6.1)
SWEP.WorldAng = Angle(0, 0, 0)
SWEP.attPos = Vector(2.7, 2, 25)
SWEP.attAng = Angle(0.5,-0.3,0)
SWEP.UseCustomWorldModel = true
SWEP.lengthSub = 25
SWEP.DistSound = "arccw_go/glock18/glock18-1-distant.wav"
SWEP.holsteredBone = "ValveBiped.Bip01_Pelvis"
SWEP.holsteredPos = Vector(12, 20, -3.5)
SWEP.holsteredAng = Angle(0, -90, -90)
SWEP.RecoilAnim = 0.3