SWEP.Base = "homigrad_base"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.PrintName = "Desert Eagle"
SWEP.Author = "Homigrad"
SWEP.Instructions = "\n8 выстрелов в секунду\n40 Урона\n0.05 Разброс"
SWEP.Category = "Оружие - Пистолеты"
SWEP.Slot = 2
SWEP.SlotPos = 2
SWEP.ViewModel = ""
SWEP.WorldModel = "models/weapons/arccw_go/v_pist_deagle.mdl"

SWEP.weaponInvCategory = 2
SWEP.ShellEject = "EjectBrass_9mm"
SWEP.Primary.ClipSize = 7
SWEP.Primary.DefaultClip = 7
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = ".50 Action Express"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 40
SWEP.Primary.Sound = {"arccw_go/deagle/deagle-1.wav", 75, 100, 100}
SWEP.Primary.Force = 35
SWEP.Primary.Spread = 0.05
SWEP.Primary.Wait = 1 / 6
SWEP.ReloadTime = 2.3
SWEP.DeploySnd = {"homigrad/weapons/draw_pistol.mp3", 55, 100, 110}
SWEP.HolsterSnd = {"homigrad/weapons/holster_pistol.mp3", 55, 100, 110}
SWEP.HoldType = "revolver"
SWEP.ZoomPos = Vector(-1.65, -1.0, 20)
SWEP.RHandPos = Vector(-12, -4.5, 5)
SWEP.LHandPos = false
SWEP.SprayRand = {Angle(-0.03, -0.03, 0), Angle(-0.05, 0.03, 0)}
SWEP.Ergonomics = 1.2
SWEP.Penetration = 7
SWEP.WorldPos = Vector(-12.6, -5.7, -6.15)
SWEP.WorldAng = Angle(0,  0, 0)
SWEP.attPos = Vector(2.74, 2, 25)
SWEP.attAng = Angle(0.5,-0.3,0)
SWEP.UseCustomWorldModel = true
SWEP.lengthSub = 25
SWEP.DistSound = "arccw_go/deagle/deagle-1-distant.wav"
SWEP.holsteredBone = "ValveBiped.Bip01_Pelvis"
SWEP.holsteredPos = Vector(12, 20, -3.5)
SWEP.holsteredAng = Angle(0, -90, -90)
SWEP.RecoilAnim = 1
SWEP.EjectPos = Vector(15,3,0)
SWEP.EjectAng = Angle(0,0,-60)
SWEP.IconAng = Angle(-25,0,0)
SWEP.IconPos = Vector(0,105,-7.7)

SWEP.BoltBone = "v_weapon.deagle_slide"
SWEP.BoltMul = Vector(0,0,-3)