SWEP.Base = "homigrad_base"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.PrintName = "Five-Seven"
SWEP.Author = "Homigrad"
SWEP.Instructions = "\n6 выстрелов в секунду\n25 Урона\n0.0075 Разброс"
SWEP.Category = "Оружие - Пистолеты"
SWEP.Slot = 2
SWEP.SlotPos = 2
SWEP.ViewModel = ""
SWEP.WorldModel = "models/weapons/arccw_go/v_pist_fiveseven.mdl"

SWEP.weaponInvCategory = 2
SWEP.ShellEject = "EjectBrass_9mm"
SWEP.Primary.ClipSize = 20
SWEP.Primary.DefaultClip = 20
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "5.7x28 mm"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 35
SWEP.Primary.Sound = {"arccw_go/fiveseven/fiveseven_01.wav", 75, 100, 100}
SWEP.Primary.Force = 25
SWEP.Primary.Spread = 0.075
SWEP.Primary.Wait = 1 / 8
SWEP.ReloadTime = 2.3
SWEP.DeploySnd = {"homigrad/weapons/draw_pistol.mp3", 55, 100, 110}
SWEP.HolsterSnd = {"homigrad/weapons/holster_pistol.mp3", 55, 100, 110}
SWEP.HoldType = "revolver"
SWEP.ZoomPos = Vector(-0.35, 0, 20)
SWEP.RHandPos = Vector(-5, -0.5, -1)
SWEP.LHandPos = false
SWEP.SprayRand = {Angle(-0.03, -0.03, 0), Angle(-0.05, 0.03, 0)}
SWEP.Ergonomics = 1.2
SWEP.Penetration = 7
SWEP.WorldPos = Vector(-13, -4.1, -6.1)
SWEP.WorldAng = Angle(0, 0, 0)
SWEP.attPos = Vector(2.7, 1, 25)
SWEP.attAng = Angle(0.5,-0.3,0)
SWEP.UseCustomWorldModel = true
SWEP.lengthSub = 25
SWEP.DistSound = "arccw_go/fiveseven/fiveseven-1-distant.wav"
SWEP.holsteredBone = "ValveBiped.Bip01_Pelvis"
SWEP.holsteredPos = Vector(12, 20, -3.5)
SWEP.holsteredAng = Angle(0, -90, -90)
SWEP.RecoilAnim = 0.9
SWEP.EjectPos = Vector(17,3,-0.5)
SWEP.EjectAng = Angle(0,0,-60)
SWEP.IconAng = Angle(-25,0,0)
SWEP.IconPos = Vector(1.1,110,-7)

SWEP.BoltBone = "v_weapon.fiveSeven_slide"
SWEP.BoltMul = Vector(0,0,-2)